### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by Jamesking56** [pa11y/pa11y-dashboard#253]
Provide a `Dockerfile` and published Docker image to make it easier for developers to run the Dashboard locally.

**Comment by ghost** [comment]
Hey, there are a few projects already out there attempting to do this. I started with work done by https://github.com/RobLoach/docker-pa11y and I am experimenting with updating here https://github.com/wavemotionio/pa11y-docker.  The result is working well locally but I am not having any luck deploying it to the cloud.

You can do the following and then go to http://localhost:80 to see it in action.
 ```
git clone https://github.com/wavemotionio/pa11y-docker
cd pa11y-docker
docker-compose up
```

The problem is when I try to use the same docker-compose.yml script using an Azure App Service we are getting a protocol error:
`It looks like you are trying to access MongoDB over HTTP on the native driver port`

This must have something to do with Azure Cloud but I cannot pinpoint yet. I might need to replace the mongodb instance with a mongolab connection string.

Dockerfile
```
FROM node:12

RUN apt-get update -y && apt-get upgrade -y && apt-get install net-tools -y && apt-get install gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget -y

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
USER node

WORKDIR /home/node/app
RUN git clone https://github.com/pa11y/pa11y-dashboard.git && cd pa11y-dashboard && npm i

EXPOSE 4000
EXPOSE 3000

WORKDIR /home/node/app/pa11y-dashboard
COPY production.json ./config/production.json

CMD NODE_ENV=production node index.js
```

Docker-compose.yml
```
version: "3.7"
services:
  database:
    image: mongo
    volumes: 
      - mongo-volume:/pa11ydata
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
  web:
    depends_on:
      - database
    image: pallespm/pa11y-docker
    # build: .
    ports:
      - "80:4000"
    restart: always
volumes:
  mongo-volume:
```
